// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using OrderAI_Dotnet.Data;

#nullable disable

namespace OrderAI_Dotnet.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OrderAI_Dotnet.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                    
                    b.Property<string>("nome")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");
                    
                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");
                    
                    b.Property<string>("senha")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");
                    
                    b.Property<string>("telefone")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");
                    
                    b.Property<string>("endereco")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");
                    
                    b.Property<string>("cep")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("cidade")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");
                    
                    b.Property<string>("estado")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("cpf")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");
                    
                    b.Property<string>("dataNascimento")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("dataCadastro")
                        .HasColumnType("NVARCHAR2(2000)");
                    
                    b.Property<string>("sexo")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.ToTable("TabelaUsuario");
                });
            modelBuilder.Entity("OrderAI_Dotnet.Models.Pedido", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("NUMBER(10)");

                OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                
                b.Property<decimal>("ValorTotal")
                    .HasColumnType("DECIMAL(10, 2)");
                
                b.Property<decimal>("FreteEntrega")
                    .HasColumnType("DECIMAL(10, 2)");

                b.Property<string>("DataEntrega")
                    .HasColumnType("NVARCHAR2(2000)");

                b.Property<string>("DataPedido")
                    .HasColumnType("NVARCHAR2(2000)");

                b.HasKey("Id");

                b.ToTable("TabelaPedido");
            });
            
            modelBuilder.Entity("OrderAI_Dotnet.Models.ItemPedido", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("NUMBER(10)");

                OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<string>("nome")
                    .IsRequired()
                    .HasColumnType("NVARCHAR2(2000)");

                b.Property<string>("descricao")
                    .IsRequired()
                    .HasColumnType("NVARCHAR2(2000)");

                b.Property<int>("quantidade")
                    .IsRequired()
                    .HasColumnType("NUMBER(10)");

                b.Property<decimal>("preco")
                    .IsRequired()
                    .HasColumnType("DECIMAL(10,2)");
                
                b.Property<string>("recomendacao")
                    .IsRequired()
                    .HasColumnType("NVARCHAR2(2000)");

                b.HasKey("Id");

                b.ToTable("TabelaItemPedido");
            });

            modelBuilder.Entity("OrderAI_Dotnet.Models.Pagamento", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("NUMBER(10)");

                OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<string>("num_cartao")
                    .IsRequired()
                    .HasColumnType("NVARCHAR2(2000)");

                b.Property<string>("nome_cartao")
                    .IsRequired()
                    .HasColumnType("NVARCHAR2(2000)");

                b.Property<string>("data_validade")
                    .IsRequired()
                    .HasColumnType("NVARCHAR2(2000)");

                b.Property<int>("cvv")
                    .IsRequired()
                    .HasColumnType("NUMBER(10)");
                
                b.Property<string>("apelido_cartao")
                    .IsRequired()
                    .HasColumnType("NVARCHAR2(2000)");

                b.HasKey("Id");

                b.ToTable("TabelaPagamento");
            });

#pragma warning restore 612, 618
        }
    }
}
